# Use the official Node.js image as the base image
FROM node:16

ADD package.json /tmp/package.json

ADD yarn.lock /tmp/yarn.lock


RUN rm -rf build 
RUN cd /tmp && yarn install
ADD ./ /src
RUN rm -rf src/node_modules && cp -a /tmp/node_modules /src/
WORKDIR /src


# Build the Next.js application
RUN yarn build

# Expose the port the app runs on
EXPOSE 3000


# Start the Next.js application
CMD ["npm", "start"]